// webgis/src/app/paginas/webgis/componentes/basemap/basemap.component.ts
import { Component, ElementRef, OnInit, ViewChild } from '@angular/core';
import { MapaService } from 'src/app/services/mapa.service';
import {
  BasemapService,
  BasemapOption,
} from 'src/app/services/basemap.service';
import { Basemap } from 'src/app/models/basemap.model';
import Map from 'ol/Map';
import TileLayer from 'ol/layer/Tile';
import XYZ from 'ol/source/XYZ';
import TileWMS from 'ol/source/TileWMS';
import { CommonModule } from '@angular/common';
import { MatTooltipModule } from '@angular/material/tooltip';
import { FetchBasemapsService } from 'src/app/services/api/fetch.basemaps.service';
import { catchError, of } from 'rxjs';

@Component({
  selector: 'app-basemap',
  templateUrl: './basemap.component.html',
  styleUrls: ['./basemap.component.scss'],
  standalone: true,
  imports: [CommonModule, MatTooltipModule],
})
export class BasemapComponent implements OnInit {
  @ViewChild('mapElement') mapElement!: ElementRef;
  map: Map | undefined;

  expanded = false;
  defaultBasemap!: BasemapOption;
  geoserverBasemaps: BasemapOption[] = [];
  externalBasemaps: BasemapOption[] = this.getFixedBasemaps();

  constructor(
    private mapaService: MapaService,
    private basemapService: BasemapService,
    private fetchBasemapsService: FetchBasemapsService,
  ) {}

  ngOnInit(): void {
    this.defaultBasemap = this.externalBasemaps[0];

    this.loadBasemaps();

    // Atualizar o BasemapService com os basemaps deste componente
    this.basemapService.setBasemaps(this.getAllBasemaps());

    this.mapaService.getMapaObservable().subscribe((mapa) => {
      this.map = mapa;
      const preferredDefaultBasemap = this.getPreferredDefaultBasemap();
      if (preferredDefaultBasemap) {
        this.applyBasemapToMap(preferredDefaultBasemap, false);
        return;
      }
      this.syncDefaultBasemapFromCurrentLayer();
    });

    // Subscribe to basemap changes triggered elsewhere (e.g., dialogs)
    this.mapaService.getBasemapObservable().subscribe((basemapKey) => {
      if (!basemapKey) return;
      const match = this.getAllBasemaps().find(
        (b) => this.getBasemapKey(b) === basemapKey || b.source === basemapKey,
      );
      if (match) {
        this.defaultBasemap = match;
      }
    });

    this.basemapService.getBasemapsRefreshObservable().subscribe(() => {
      this.loadBasemaps();
    });
  }

  toggleExpansion() {
    this.expanded = !this.expanded;
  }

  changeBasemap(selectedBasemap: BasemapOption) {
    this.applyBasemapToMap(selectedBasemap, true);
  }

  private getBasemapKey(basemap: BasemapOption): string {
    if (this.isWmsBasemap(basemap)) {
      return `wms:${basemap.source}?${this.serializeWmsParams(basemap.wmsParams ?? {})}`;
    }

    return `xyz:${basemap.source}`;
  }

  private loadBasemaps(): void {
    this.fetchBasemapsService
      .getBasemaps()
      .pipe(
        catchError((error) => {
          console.error('Erro ao buscar basemaps cadastrados:', error);
          return of([]);
        }),
      )
      .subscribe((basemaps) => {
        this.geoserverBasemaps = basemaps
          .filter((basemap: Basemap) => basemap.isActive !== false)
          .sort((a: Basemap, b: Basemap) => {
            const orderDifference =
              (a.order ?? Number.MAX_SAFE_INTEGER) -
              (b.order ?? Number.MAX_SAFE_INTEGER);
            if (orderDifference !== 0) {
              return orderDifference;
            }

            return a.name.localeCompare(b.name);
          })
          .map((basemap: Basemap) => ({
            name: basemap.name,
            thumbnail: basemap.thumbnail,
            source: basemap.source,
            type: 'wms',
            wmsParams: basemap.wmsParams ?? undefined,
            order: basemap.order,
            isDefault: basemap.isDefault,
          }));

        this.basemapService.setBasemaps(this.getAllBasemaps());

        const preferredDefaultBasemap = this.getPreferredDefaultBasemap();
        if (preferredDefaultBasemap) {
          this.defaultBasemap = preferredDefaultBasemap;
          this.applyBasemapToMap(preferredDefaultBasemap, false);
          return;
        }

        if (!this.defaultBasemap && this.getAllBasemaps().length > 0) {
          this.defaultBasemap = this.getAllBasemaps()[0];
        }

        this.syncDefaultBasemapFromCurrentLayer();
      });
  }

  private getPreferredDefaultBasemap(): BasemapOption | null {
    return this.geoserverBasemaps.find((basemap) => basemap.isDefault) ?? null;
  }

  private applyBasemapToMap(
    selectedBasemap: BasemapOption,
    closePanel: boolean,
  ): void {
    if (!selectedBasemap || !selectedBasemap.source) {
      return;
    }

    this.defaultBasemap = selectedBasemap;

    if (!this.map) {
      return;
    }

    const selectedKey = this.getBasemapKey(selectedBasemap);
    const currentKey = this.getBasemapKeyFromLayer(
      this.map.getLayers().item(0) as TileLayer<any> | null,
    );

    if (currentKey !== selectedKey) {
      const source = this.isWmsBasemap(selectedBasemap)
        ? new TileWMS({
            url: selectedBasemap.source,
            params: selectedBasemap.wmsParams ?? {},
            crossOrigin: 'anonymous',
          })
        : new XYZ({
            url: selectedBasemap.source,
            crossOrigin: 'anonymous',
            maxZoom: 19,
          });

      const newBase = new TileLayer({
        source,
        preload: 1,
      });
      newBase.set('transition', 0);
      this.map.getLayers().setAt(0, newBase);
    }

    this.mapaService.updateBasemap(selectedKey);
    if (closePanel) {
      this.expanded = false;
    }
  }

  isSelectedBasemap(basemap: BasemapOption): boolean {
    return (
      this.getBasemapKey(this.defaultBasemap) === this.getBasemapKey(basemap)
    );
  }

  private getAllBasemaps(): BasemapOption[] {
    return [...this.geoserverBasemaps, ...this.externalBasemaps];
  }

  private getFixedBasemaps(): BasemapOption[] {
    return [
      {
        name: 'OpenStreetMap',
        thumbnail: 'https://tile.openstreetmap.org/8/99/142.png',
        source: '/tile-proxy/{z}/{x}/{y}.png',
      },
      {
        name: 'Esri Living Atlas',
        thumbnail:
          'https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/8/142/99.png',
        source: '/imagery/tile/{z}/{y}/{x}.png',
      },
      {
        name: 'World Topography',
        thumbnail:
          'https://services.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer/tile/8/142/99.png',
        source: '/topo/tile/{z}/{y}/{x}.png',
      },
      {
        name: 'World Physical',
        thumbnail:
          'https://services.arcgisonline.com/arcgis/rest/services/World_Physical_Map/MapServer/tile/8/142/99.png',
        source: '/physical/tile/{z}/{y}/{x}.png',
      },
      {
        name: 'World Street',
        thumbnail:
          'https://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer/tile/8/142/99.png',
        source: '/street/tile/{z}/{y}/{x}.png',
      },
    ];
  }

  private syncDefaultBasemapFromCurrentLayer(): void {
    try {
      const baseLayer = this.map?.getLayers().item(0) as TileLayer<any> | null;
      const currentKey = this.getBasemapKeyFromLayer(baseLayer);
      if (currentKey) {
        const match = this.getAllBasemaps().find(
          (b) => this.getBasemapKey(b) === currentKey,
        );
        if (match) {
          this.defaultBasemap = match;
        }
        this.mapaService.updateBasemap(
          match ? this.getBasemapKey(match) : currentKey,
        );
      }
    } catch {}
  }

  private isWmsBasemap(basemap: BasemapOption): boolean {
    return (
      basemap.type === 'wms' ||
      !!basemap.wmsParams ||
      basemap.source.includes('/wms')
    );
  }

  private getBasemapKeyFromLayer(
    baseLayer: TileLayer<any> | null | undefined,
  ): string | null {
    const source: any = baseLayer?.getSource();
    if (!source) return null;

    const url = this.getSourceUrl(source);
    if (!url) return null;

    const isWmsSource = typeof source.getParams === 'function';
    if (isWmsSource) {
      const params = source.getParams() ?? {};
      return `wms:${url}?${this.serializeWmsParams(params)}`;
    }

    return `xyz:${url}`;
  }

  private getSourceUrl(source: any): string | null {
    if (typeof source.getUrls === 'function') {
      const urls = source.getUrls();
      if (Array.isArray(urls) && urls.length > 0) return urls[0];
    }

    if (typeof source.getUrl === 'function') {
      const url = source.getUrl();
      if (typeof url === 'string') return url;
    }

    return source?.url ?? null;
  }

  private serializeWmsParams(params: Record<string, any>): string {
    return Object.entries(params)
      .map(
        ([key, value]) => [String(key).toUpperCase(), String(value)] as const,
      )
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([key, value]) => `${key}=${value}`)
      .join('&');
  }
}

<div class="basemap-wrapper">
  <!-- Thumbnail inline dentro da pill bar -->
  <div class="basemap-thumb" (click)="toggleExpansion()" title="Trocar basemap" [class.active]="expanded">
    <img [src]="defaultBasemap.thumbnail" alt="Basemap atual" class="basemap-thumb-img">
  </div>

  <!-- Painel expandido — flutua acima da pill bar -->
  <div class="expanded-panel" *ngIf="expanded">

    <div class="basemap-section" *ngIf="geoserverBasemaps.length > 0">
      <div class="section-title">basemaps do sistema</div>
      <div class="basemap-grid geoserver-grid">
        <div
          *ngFor="let basemap of geoserverBasemaps"
          (click)="changeBasemap(basemap)"
          class="basemap-card"
          [class.selected]="isSelectedBasemap(basemap)">
          <div class="basemap-image-wrap">
            <img [src]="basemap.thumbnail" alt="Thumbnail do Basemap" class="basemap-image" [matTooltip]="'Basemap: ' + basemap.name">
            <div class="basemap-label-overlay">{{ basemap.name }}</div>
          </div>
        </div>
      </div>
    </div>

    <div class="section-divider" *ngIf="geoserverBasemaps.length > 0 && externalBasemaps.length > 0"></div>

    <div class="basemap-section" *ngIf="externalBasemaps.length > 0">
      <div class="section-title">basemaps externos</div>
      <div class="basemap-grid external-grid">
        <div
          *ngFor="let basemap of externalBasemaps"
          (click)="changeBasemap(basemap)"
          class="basemap-card"
          [class.selected]="isSelectedBasemap(basemap)">
          <div class="basemap-image-wrap">
            <img [src]="basemap.thumbnail" alt="Thumbnail do Basemap" class="basemap-image" [matTooltip]="'Basemap: ' + basemap.name">
            <div class="basemap-label-overlay">{{ basemap.name }}</div>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

// webgis-react/src/components/webgis/Basemap.tsx
// GEO Portal — Basemap (portado de basemap.component.ts)
// Troca a camada base do mapa entre basemaps do sistema (WMS) e externos (XYZ).
import { useEffect, useState } from 'react';
import TileLayer from 'ol/layer/Tile';
import XYZ from 'ol/source/XYZ';
import TileWMS from 'ol/source/TileWMS';
import { api } from '../../lib/api';
import { useMapa } from '../../contexts/MapaContext';
import './Basemap.css';

interface BasemapOption {
  key: string;
  name: string;
  thumbnail: string;
  source: string;
  type: 'wms' | 'xyz';
  wmsParams?: Record<string, string>;
}

interface BasemapApiItem {
  id: string;
  name: string;
  thumbnail: string;
  source: string;
  wmsParams?: Record<string, string> | null;
  order?: number | null;
  isDefault?: boolean;
  isActive?: boolean;
}

const EXTERNAL_BASEMAPS: BasemapOption[] = [
  {
    key: 'xyz:osm',
    name: 'OpenStreetMap',
    type: 'xyz',
    source: 'https://tile.openstreetmap.org/{z}/{x}/{y}.png',
    thumbnail: 'https://tile.openstreetmap.org/8/99/142.png',
  },
  {
    key: 'xyz:esri-imagery',
    name: 'Esri Living Atlas',
    type: 'xyz',
    source:
      'https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}.png',
    thumbnail:
      'https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/tile/8/142/99.png',
  },
  {
    key: 'xyz:esri-topo',
    name: 'World Topography',
    type: 'xyz',
    source:
      'https://services.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer/tile/{z}/{y}/{x}.png',
    thumbnail:
      'https://services.arcgisonline.com/arcgis/rest/services/World_Topo_Map/MapServer/tile/8/142/99.png',
  },
  {
    key: 'xyz:esri-physical',
    name: 'World Physical',
    type: 'xyz',
    source:
      'https://services.arcgisonline.com/arcgis/rest/services/World_Physical_Map/MapServer/tile/{z}/{y}/{x}.png',
    thumbnail:
      'https://services.arcgisonline.com/arcgis/rest/services/World_Physical_Map/MapServer/tile/8/142/99.png',
  },
  {
    key: 'xyz:esri-street',
    name: 'World Street',
    type: 'xyz',
    source:
      'https://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer/tile/{z}/{y}/{x}.png',
    thumbnail:
      'https://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer/tile/8/142/99.png',
  },
];

export default function Basemap() {
  const { mapa, setBasemapUrl } = useMapa();
  const [expanded, setExpanded] = useState(false);
  const [geoserverBasemaps, setGeoserverBasemaps] = useState<BasemapOption[]>([]);
  const [selectedKey, setSelectedKey] = useState<string>(EXTERNAL_BASEMAPS[0].key);

  useEffect(() => {
    let cancelled = false;
    api
      .get('/fetch-basemaps')
      .then((data) => {
        if (cancelled) return;
        const items = (data as { basemaps?: BasemapApiItem[] }).basemaps ?? [];
        const parsed = items
          .filter((b) => b.isActive !== false)
          .sort(
            (a, b) =>
              (a.order ?? Number.MAX_SAFE_INTEGER) - (b.order ?? Number.MAX_SAFE_INTEGER) ||
              a.name.localeCompare(b.name),
          )
          .map((b): BasemapOption => ({
            key: `wms:${b.id}`,
            name: b.name,
            thumbnail: b.thumbnail,
            source: b.source,
            type: 'wms',
            wmsParams: b.wmsParams ?? {},
          }));
        setGeoserverBasemaps(parsed);
      })
      .catch(() => setGeoserverBasemaps([]));

    return () => {
      cancelled = true;
    };
  }, []);

  const allBasemaps = [...geoserverBasemaps, ...EXTERNAL_BASEMAPS];
  const selected = allBasemaps.find((b) => b.key === selectedKey) ?? EXTERNAL_BASEMAPS[0];

  function changeBasemap(basemap: BasemapOption) {
    if (mapa && basemap.key !== selectedKey) {
      const source =
        basemap.type === 'wms'
          ? new TileWMS({
              url: basemap.source,
              params: basemap.wmsParams ?? {},
              crossOrigin: 'anonymous',
            })
          : new XYZ({ url: basemap.source, maxZoom: 19 });

      const newLayer = new TileLayer({ source, preload: 1 });
      mapa.getLayers().setAt(0, newLayer);
      setBasemapUrl(basemap.source);
    }

    setSelectedKey(basemap.key);
    setExpanded(false);
  }

  return (
    <div className="basemap-wrapper">
      <div
        className={`basemap-thumb${expanded ? ' basemap-thumb-active' : ''}`}
        onClick={() => setExpanded((v) => !v)}
        title="Trocar basemap"
      >
        <img src={selected.thumbnail} alt="Basemap atual" className="basemap-thumb-img" />
      </div>

      {expanded && (
        <div className="basemap-panel">
          {geoserverBasemaps.length > 0 && (
            <div className="basemap-section">
              <div className="basemap-section-title">basemaps do sistema</div>
              <div className="basemap-grid basemap-grid-geoserver">
                {geoserverBasemaps.map((b) => (
                  <button
                    type="button"
                    key={b.key}
                    className={`basemap-card${b.key === selectedKey ? ' basemap-card-selected' : ''}`}
                    onClick={() => changeBasemap(b)}
                  >
                    <img src={b.thumbnail} alt={b.name} className="basemap-image" title={`Basemap: ${b.name}`} />
                    <div className="basemap-label">{b.name}</div>
                  </button>
                ))}
              </div>
            </div>
          )}

          {geoserverBasemaps.length > 0 && <div className="basemap-divider" />}

          <div className="basemap-section">
            <div className="basemap-section-title">basemaps externos</div>
            <div className="basemap-grid basemap-grid-external">
              {EXTERNAL_BASEMAPS.map((b) => (
                <button
                  type="button"
                  key={b.key}
                  className={`basemap-card${b.key === selectedKey ? ' basemap-card-selected' : ''}`}
                  onClick={() => changeBasemap(b)}
                >
                  <img src={b.thumbnail} alt={b.name} className="basemap-image" title={`Basemap: ${b.name}`} />
                  <div className="basemap-label">{b.name}</div>
                </button>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
