// webgis/src/app/paginas/webgis/componentes/customzoom/customzoom.component.ts
import { Component, OnInit, OnDestroy, ChangeDetectorRef } from '@angular/core';
import { MapaService } from 'src/app/services/mapa.service';
import { Map } from 'ol';
import { getPointResolution } from 'ol/proj';
import { Observable, Subscription } from 'rxjs';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-custom-zoom',
  templateUrl: './customzoom.component.html',
  styleUrls: ['./customzoom.component.scss'],
  standalone: true,
  imports: [MatIconModule, MatButtonModule],
})
export class CustomZoomComponent implements OnInit, OnDestroy {
  private map$!: Observable<Map>;
  private mapSubscription!: Subscription;

  private readonly DPI = 96;
  private readonly INCHES_PER_METER = 39.37008;
  private readonly SCALE_STEP = 1000;

  currentScale: number = 900000;
  isZooming: boolean = false;

  constructor(
    private mapaService: MapaService,
    private cdr: ChangeDetectorRef,
  ) {}

  ngOnInit(): void {
    this.map$ = this.mapaService.getMapaObservable();
    this.mapSubscription = this.map$.subscribe((map: Map) => {
      if (map) {
        this.currentScale = 900000;
      }
    });

    this.mapaService.getScaleObservable().subscribe((scale: number) => {
      if (scale !== this.currentScale && !this.isZooming) {
        this.currentScale = scale;
      }
    });
  }

  ngOnDestroy(): void {
    if (this.mapSubscription) {
      this.mapSubscription.unsubscribe();
    }
  }

  zoomIn(): void {
    this.map$ = this.mapaService.getMapaObservable();
    this.map$.subscribe((map: Map) => {
      if (map) {
        this.isZooming = true;

        this.mapaService.setManualZoom(true);

        const newScale = Math.max(
          this.currentScale - this.SCALE_STEP,
          this.SCALE_STEP,
        );

        this.currentScale = newScale;

        this.mapaService.updateScale(newScale);

        this.applyScale(map, newScale);

        setTimeout(() => {
          this.isZooming = false;
        }, 300);
      }
    });
  }

  zoomOut(): void {
    this.map$ = this.mapaService.getMapaObservable();
    this.map$.subscribe((map: Map) => {
      if (map) {
        this.isZooming = true;

        this.mapaService.setManualZoom(true);

        const newScale = this.currentScale + this.SCALE_STEP;

        this.currentScale = newScale;

        this.mapaService.updateScale(newScale);

        this.applyScale(map, newScale);

        setTimeout(() => {
          this.isZooming = false;
        }, 300);
      }
    });
  }

  private applyScale(map: Map, targetScale: number): void {
    const view = map.getView();
    const center = view.getCenter();
    const projection = view.getProjection();

    if (!center) return;

    try {
      let targetResolution = targetScale / (this.DPI * this.INCHES_PER_METER);

      if (projection.getUnits() === 'degrees') {
        const currentPointResolution = getPointResolution(
          projection,
          1,
          center,
        );
        targetResolution = targetResolution / currentPointResolution;
      }

      view.animate({
        resolution: targetResolution,
        duration: 250,
        easing: (t) => t * (2 - t),
      });
    } catch (error) {
      const targetResolution = targetScale / (this.DPI * this.INCHES_PER_METER);
      view.animate({
        resolution: targetResolution,
        duration: 250,
      });
    }
  }

  syncWithScale(scale: number): void {
    this.currentScale = scale;
    this.cdr.detectChanges();
  }
  getCurrentPosition(): number {
    const minScale = 1000;
    const maxScale = 2000000;

    const percentage =
      ((this.currentScale - minScale) / (maxScale - minScale)) * 100;
    return Math.max(0, Math.min(100, percentage));
  }

  onRulerClick(event: MouseEvent): void {
    if (this.isZooming) return;

    const rect = (event.currentTarget as HTMLElement).getBoundingClientRect();
    const clickY = event.clientY - rect.top;
    const percentage = (clickY / rect.height) * 100;

    const minScale = 1000;
    const maxScale = 2000000;

    const targetScale = minScale + (percentage / 100) * (maxScale - minScale);

    const roundedScale = Math.round(targetScale / 1000) * 1000;

    this.jumpToScale(Math.max(roundedScale, 1000));
  }
  jumpToScale(targetScale: number): void {
    if (this.isZooming || targetScale === this.currentScale) return;

    this.map$ = this.mapaService.getMapaObservable();
    this.map$.subscribe((map: Map) => {
      if (map) {
        this.isZooming = true;

        this.mapaService.setManualZoom(true);

        this.currentScale = targetScale;

        this.mapaService.updateScale(targetScale);

        this.applyScale(map, targetScale);

        setTimeout(() => {
          this.isZooming = false;
        }, 300);
      }
    });
  }
}

<div class="custom-zoom-controls">
  <button mat-icon-button class="zoom-button zoom-in" (click)="zoomIn()" [disabled]="isZooming" title="Zoom In (-1000)"
    aria-label="Zoom In">
    <mat-icon>add</mat-icon>
  </button>

  <div class="scale-ruler-simple">
    <div class="ruler-bar" (click)="onRulerClick($event)">

      <div class="ruler-marks">
        <div class="ruler-line" style="top: 95%"></div>
        <div class="ruler-line" style="top: 90%"></div>
        <div class="ruler-line" style="top: 85%"></div>
        <div class="ruler-line" style="top: 80%"></div>
        <div class="ruler-line" style="top: 75%"></div>
        <div class="ruler-line" style="top: 70%"></div>
        <div class="ruler-line" style="top: 65%"></div>
        <div class="ruler-line" style="top: 60%"></div>
        <div class="ruler-line" style="top: 55%"></div>
        <div class="ruler-line" style="top: 50%"></div>
        <div class="ruler-line" style="top: 45%"></div>
        <div class="ruler-line" style="top: 40%"></div>
        <div class="ruler-line" style="top: 35%"></div>
        <div class="ruler-line" style="top: 30%"></div>
        <div class="ruler-line" style="top: 25%"></div>
        <div class="ruler-line" style="top: 20%"></div>
        <div class="ruler-line" style="top: 15%"></div>
        <div class="ruler-line" style="top: 10%"></div>
        <div class="ruler-line" style="top: 5%"></div>
      </div>

      <div class="current-position" [style.top.%]="getCurrentPosition()">
        {{currentScale / 1000}}K
      </div>
    </div>
  </div>

  <button mat-icon-button class="zoom-button zoom-out" (click)="zoomOut()" [disabled]="isZooming"
    title="Zoom Out (+1000)" aria-label="Zoom Out">
    <mat-icon>remove</mat-icon>
  </button>
</div>

// webgis-react/src/components/webgis/CustomZoom.tsx
// GEO Portal — CustomZoom (portado de customzoom.component.ts)
// Botões +/- e régua de escala vertical para zoom manual do mapa.
import { useState, type MouseEvent } from 'react';
import { getPointResolution } from 'ol/proj';
import { useMapa } from '../../contexts/MapaContext';
import './CustomZoom.css';

const DPI = 96;
const INCHES_PER_METER = 39.37008;
const SCALE_STEP = 1000;
const MIN_SCALE = 1000;
const MAX_SCALE = 2000000;
const RULER_MARKS = Array.from({ length: 19 }, (_, i) => 95 - i * 5);

export default function CustomZoom() {
  const { mapa, escala, setEscala, setManualZoom } = useMapa();
  const [isZooming, setIsZooming] = useState(false);

  function applyScale(targetScale: number) {
    if (!mapa) return;
    const view = mapa.getView();
    const center = view.getCenter();
    const projection = view.getProjection();
    if (!center) return;

    let targetResolution = targetScale / (DPI * INCHES_PER_METER);
    try {
      if (projection.getUnits() === 'degrees') {
        const currentPointResolution = getPointResolution(projection, 1, center);
        targetResolution = targetResolution / currentPointResolution;
      }
    } catch {
      // usa resolução linear como alternativa
    }

    view.animate({
      resolution: targetResolution,
      duration: 250,
      easing: (t) => t * (2 - t),
    });
  }

  function jumpToScale(targetScale: number) {
    if (isZooming || !mapa || targetScale === escala) return;

    setIsZooming(true);
    setManualZoom(true);
    setEscala(targetScale);
    applyScale(targetScale);

    setTimeout(() => {
      setIsZooming(false);
      setManualZoom(false);
    }, 300);
  }

  function zoomIn() {
    jumpToScale(Math.max(escala - SCALE_STEP, SCALE_STEP));
  }

  function zoomOut() {
    jumpToScale(escala + SCALE_STEP);
  }

  function onRulerClick(e: MouseEvent<HTMLDivElement>) {
    if (isZooming) return;
    const rect = e.currentTarget.getBoundingClientRect();
    const clickY = e.clientY - rect.top;
    const percentage = (clickY / rect.height) * 100;
    const targetScale = MIN_SCALE + (percentage / 100) * (MAX_SCALE - MIN_SCALE);
    const roundedScale = Math.round(targetScale / 1000) * 1000;
    jumpToScale(Math.max(roundedScale, MIN_SCALE));
  }

  const position = Math.max(0, Math.min(100, ((escala - MIN_SCALE) / (MAX_SCALE - MIN_SCALE)) * 100));

  return (
    <div className="customzoom-controls">
      <button
        type="button"
        className="customzoom-btn customzoom-in"
        onClick={zoomIn}
        disabled={isZooming}
        title="Zoom In (-1000)"
        aria-label="Zoom In"
      >
        +
      </button>

      <div className="customzoom-ruler">
        <div className="customzoom-ruler-bar" onClick={onRulerClick}>
          <div className="customzoom-ruler-marks">
            {RULER_MARKS.map((top) => (
              <div key={top} className="customzoom-ruler-line" style={{ top: `${top}%` }} />
            ))}
          </div>
          <div className="customzoom-position" style={{ top: `${position}%` }}>
            {(escala / 1000).toFixed(0)}K
          </div>
        </div>
      </div>

      <button
        type="button"
        className="customzoom-btn customzoom-out"
        onClick={zoomOut}
        disabled={isZooming}
        title="Zoom Out (+1000)"
        aria-label="Zoom Out"
      >
        −
      </button>
    </div>
  );
}
