// webgis/src/app/paginas/webgis/componentes/drawing/drawing.component.ts
import { Component, OnInit, OnDestroy } from '@angular/core';
import { Vector as VectorSource } from 'ol/source';
import { Vector as VectorLayer } from 'ol/layer';
import { Draw, Modify, Snap } from 'ol/interaction';
import { Circle as CircleStyle, Fill, Stroke, Style } from 'ol/style';
import { LineString, SimpleGeometry } from 'ol/geom';
import { MapaService } from 'src/app/services/mapa.service';
import { FormControl, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { MatSelectModule } from '@angular/material/select';
import { MatOptionModule } from '@angular/material/core';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import {
  MAT_SLIDE_TOGGLE_DEFAULT_OPTIONS,
  MatSlideToggleModule,
} from '@angular/material/slide-toggle';
import { MatSliderModule } from '@angular/material/slider';
import { GeometryFunction, SketchCoordType } from 'ol/interaction/Draw';
import { Observable, Subscription } from 'rxjs';
import { Map } from 'ol';
import { filter } from 'rxjs/operators';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';

@Component({
  selector: 'app-drawing',
  standalone: true,
  imports: [
    MatFormFieldModule,
    MatSelectModule,
    MatSliderModule,
    MatInputModule,
    MatSlideToggleModule,
    MatOptionModule,
    FormsModule,
    ReactiveFormsModule,
    MatIconModule,
    MatButtonModule,
  ],
  providers: [
    {
      provide: MAT_SLIDE_TOGGLE_DEFAULT_OPTIONS,
      useValue: {
        color: '#4DA9E7',
      },
    },
  ],
  templateUrl: './drawing.component.html',
  styleUrls: ['./drawing.component.scss'],
})
export class DrawingComponent implements OnInit, OnDestroy {
  vectorLayer!: VectorLayer<VectorSource>;
  draw!: Draw;
  snap!: Snap;
  source = new VectorSource({ wrapX: false });
  lineWidth = 2;
  lineColor = '#ffcc33';
  fillColor = '#ffffff';
  fillOpacity = 1.0;
  drawType:
    | 'Selecione'
    | 'Point'
    | 'LineString'
    | 'Polygon'
    | 'Circle'
    | 'Arrow' = 'Selecione';
  freehand = false;
  clearPrevious = false;
  lineWidthControl = new FormControl(2);

  private map$!: Observable<Map>;
  private mapSubscription!: Subscription;

  constructor(private mapaService: MapaService) {}

  ngOnInit() {
    this.map$ = this.mapaService
      .getMapaObservable()
      .pipe(filter((map): map is Map => map !== null));

    this.mapSubscription = this.map$.subscribe((map) => {
      this.initializeMap(map);
      this.addInteractions(map);

      const layers = map.getLayers();
      const handleLayerAdd = () => {
        layers.un('add', handleLayerAdd);
        this.bringVectorLayerToTop(map);
        layers.on('add', handleLayerAdd);
      };

      layers.on('add', handleLayerAdd);
    });

    this.lineWidthControl.valueChanges.subscribe((value) => {
      this.lineWidth = value || 2;
      this.updateStyle();
    });
  }

  ngOnDestroy(): void {
    if (this.mapSubscription) {
      this.mapSubscription.unsubscribe();
    }
  }

  initializeMap(map: Map) {
    this.vectorLayer = new VectorLayer({
      source: this.source,
      style: this.getDefaultStyle(),
    });

    map.addLayer(this.vectorLayer);
  }

  onChangeDrawType(event: any) {
    this.drawType = event.value;
    this.updateDrawInteraction();
  }

  bringVectorLayerToTop(map: Map): void {
    map.removeLayer(this.vectorLayer);
    map.addLayer(this.vectorLayer);
  }

  addInteractions(map: Map) {
    this.updateDrawInteraction();
    const modify = new Modify({ source: this.source });
    map.addInteraction(modify);

    this.snap = new Snap({ source: this.source });
    map.addInteraction(this.snap);
  }

  updateDrawInteraction() {
    const map = this.mapaService.getMapa();
    if (!map) {
      console.error('Mapa não está disponível.');
      return;
    }

    if (this.draw) {
      map.removeInteraction(this.draw);
    }

    if (this.drawType === 'Selecione') {
      return;
    }

    let geometryFunction: GeometryFunction | undefined;
    let drawType: 'Point' | 'LineString' | 'Polygon' | 'Circle';

    if (this.drawType === 'Arrow') {
      drawType = 'LineString';
      geometryFunction = this.arrowGeometryFunction.bind(this);
    } else {
      drawType = this.drawType;
      geometryFunction = undefined;
    }

    this.draw = new Draw({
      source: this.source,
      type: drawType,
      freehand: this.freehand,
      geometryFunction: geometryFunction,
    });

    this.draw.on('drawstart', () => {
      if (this.clearPrevious) {
        this.source.clear();
      }
    });

    map.addInteraction(this.draw);
  }

  clearAllDrawings() {
    this.source.clear();
  }

  onClearPreviousChange() {
    if (this.clearPrevious) {
      this.source.clear();
    }
  }

  updateStyle() {
    if (this.vectorLayer) {
      this.vectorLayer.setStyle(this.getDefaultStyle());
    } else {
      console.error('vectorLayer is not initialized');
    }
  }

  getDefaultStyle() {
    return new Style({
      fill: new Fill({
        color: this.hexToRgba(this.fillColor, this.fillOpacity),
      }),
      stroke: new Stroke({
        color: this.lineColor,
        width: this.lineWidth,
      }),
      image: new CircleStyle({
        radius: 7,
        fill: new Fill({
          color: this.lineColor,
        }),
      }),
    });
  }

  arrowGeometryFunction(
    coordinates: SketchCoordType,
    geometry?: SimpleGeometry,
  ): SimpleGeometry {
    const start = coordinates[0] as number[];
    const end = coordinates[coordinates.length - 1] as number[];
    const dx = end[0] - start[0];
    const dy = end[1] - start[1];
    const rotation = Math.atan2(dy, dx);

    const arrowLength = 10000;

    const point1 = [
      end[0] - arrowLength * Math.cos(rotation - Math.PI / 6),
      end[1] - arrowLength * Math.sin(rotation - Math.PI / 6),
    ];
    const point2 = [
      end[0] - arrowLength * Math.cos(rotation + Math.PI / 6),
      end[1] - arrowLength * Math.sin(rotation + Math.PI / 6),
    ];

    if (!geometry || !(geometry instanceof LineString)) {
      geometry = new LineString([start, end, point1, end, point2, end]);
    } else {
      geometry.setCoordinates([start, end, point1, end, point2, end]);
    }

    return geometry;
  }

  onColorChange(event: Event, type: 'line' | 'fill'): void {
    const input = event.target as HTMLInputElement;
    const color = input?.value || '';

    if (type === 'line') {
      this.lineColor = color;
    } else if (type === 'fill') {
      this.fillColor = color;
    }

    this.updateStyle();
  }

  hexToRgba(hex: string, opacity: number): string {
    let r = 0,
      g = 0,
      b = 0;
    if (hex.length === 4) {
      r = parseInt(hex[1] + hex[1], 16);
      g = parseInt(hex[2] + hex[2], 16);
      b = parseInt(hex[3] + hex[3], 16);
    } else if (hex.length === 7) {
      r = parseInt(hex[1] + hex[2], 16);
      g = parseInt(hex[3] + hex[4], 16);
      b = parseInt(hex[5] + hex[6], 16);
    }
    return `rgba(${r},${g},${b},${opacity})`;
  }
}

<!-- ── Header ─────────────────────────────────────────────────────────────── -->
<div class="panel-header">
  <div class="panel-title">
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path d="M12 20h9M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"
            stroke="#01499B" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"/>
    </svg>
    <span class="panel-label">Desenhar</span>
  </div>
</div>

<!-- ── Tipo de desenho ────────────────────────────────────────────────────── -->
<div class="field-group">
  <span class="field-label">Tipo de desenho</span>
  <div class="select-wrap">
    <mat-select [(ngModel)]="drawType" (selectionChange)="onChangeDrawType($event)" panelClass="webgis-select-panel">
      <mat-option value="Selecione">Selecione</mat-option>
      <mat-option value="Point">Ponto</mat-option>
      <mat-option value="LineString">Linha</mat-option>
      <mat-option value="Polygon">Polígono</mat-option>
      <mat-option value="Circle">Círculo</mat-option>
      <mat-option value="Arrow">Seta</mat-option>
    </mat-select>
  </div>
</div>

<!-- ── Cores ──────────────────────────────────────────────────────────────── -->
<div class="color-row">
  <div class="color-group">
    <span class="field-label">Cor da linha</span>
    <label class="color-wrap">
      <span class="color-preview" [style.background]="lineColor"></span>
      <span class="color-label">{{ lineColor }}</span>
      <input type="color" [value]="lineColor" (input)="onColorChange($event, 'line')" class="color-input"/>
    </label>
  </div>
  <div class="color-group">
    <span class="field-label">Cor de fundo</span>
    <label class="color-wrap">
      <span class="color-preview" [style.background]="fillColor"></span>
      <span class="color-label">{{ fillColor }}</span>
      <input type="color" [value]="fillColor" (input)="onColorChange($event, 'fill')" class="color-input"/>
    </label>
  </div>
</div>

<!-- ── Espessura ──────────────────────────────────────────────────────────── -->
<div class="field-group">
  <div class="slider-header">
    <span class="field-label">Espessura da linha</span>
    <span class="slider-value">{{ lineWidth }}px</span>
  </div>
  <input type="range" class="styled-range" min="1" max="10" [(ngModel)]="lineWidth" (change)="updateStyle()"/>
</div>

<!-- ── Transparência ──────────────────────────────────────────────────────── -->
<div class="field-group">
  <div class="slider-header">
    <span class="field-label">Transparência</span>
    <span class="slider-value">{{ (fillOpacity * 100).toFixed(0) }}%</span>
  </div>
  <input type="range" class="styled-range" min="0" max="1" step="0.05" [(ngModel)]="fillOpacity" (change)="updateStyle()"/>
</div>

<!-- ── Toggles ─────────────────────────────────────────────────────────────── -->
<div class="toggles">
  <div class="toggle-row" (click)="freehand = !freehand; updateDrawInteraction()">
    <span class="toggle-text">Desenho à mão livre</span>
    <div class="toggle-wrap" [class.toggle-on]="freehand">
      <div class="toggle-track"><div class="toggle-thumb"></div></div>
    </div>
  </div>

  <div class="toggle-row" (click)="clearPrevious = !clearPrevious; onClearPreviousChange()">
    <span class="toggle-text">Limpar anteriores</span>
    <div class="toggle-wrap" [class.toggle-on]="clearPrevious">
      <div class="toggle-track"><div class="toggle-thumb"></div></div>
    </div>
  </div>
</div>

<!-- ── Ação ───────────────────────────────────────────────────────────────── -->
<button class="clear-btn" (click)="clearAllDrawings()" type="button">
  <svg width="13" height="13" viewBox="0 0 24 24" fill="none">
    <path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6" stroke="currentColor" stroke-width="1.7"
          stroke-linecap="round" stroke-linejoin="round"/>
  </svg>
  Limpar desenhos
</button>

// webgis-react/src/components/webgis/Drawing.tsx
// GEO Portal — Drawing (portado de drawing.component.ts do Angular)
// Desenho de Point/LineString/Polygon/Circle/Arrow com estilos customizáveis.
import { useEffect, useRef, useState } from 'react';
import VectorSource from 'ol/source/Vector';
import VectorLayer from 'ol/layer/Vector';
import { Draw, Modify, Snap } from 'ol/interaction';
import {
  Circle as CircleStyle,
  Fill,
  Stroke,
  Style,
} from 'ol/style';
import { LineString, type SimpleGeometry } from 'ol/geom';
import type { GeometryFunction, SketchCoordType } from 'ol/interaction/Draw';
import { useMapa } from '../../contexts/MapaContext';
import './Drawing.css';

type DrawType = 'Selecione' | 'Point' | 'LineString' | 'Polygon' | 'Circle' | 'Arrow';

const TYPES: DrawType[] = [
  'Selecione',
  'Point',
  'LineString',
  'Polygon',
  'Circle',
  'Arrow',
];

function hexToRgba(hex: string, opacity: number): string {
  let r = 0;
  let g = 0;
  let b = 0;
  if (hex.length === 4) {
    r = parseInt(hex[1] + hex[1], 16);
    g = parseInt(hex[2] + hex[2], 16);
    b = parseInt(hex[3] + hex[3], 16);
  } else if (hex.length === 7) {
    r = parseInt(hex[1] + hex[2], 16);
    g = parseInt(hex[3] + hex[4], 16);
    b = parseInt(hex[5] + hex[6], 16);
  }
  return `rgba(${r},${g},${b},${opacity})`;
}

const ARROW_LENGTH = 10000;

export default function Drawing() {
  const { mapa } = useMapa();
  const sourceRef = useRef(new VectorSource({ wrapX: false }));
  const vectorLayerRef = useRef<VectorLayer<VectorSource> | null>(null);
  const drawRef = useRef<Draw | null>(null);

  const [drawType, setDrawType] = useState<DrawType>('Selecione');
  const [freehand, setFreehand] = useState(false);
  const [clearPrevious, setClearPrevious] = useState(false);
  const [lineWidth, setLineWidth] = useState(2);
  const [lineColor, setLineColor] = useState('#ffcc33');
  const [fillColor, setFillColor] = useState('#ffffff');
  const [fillOpacity, setFillOpacity] = useState(1.0);

  useEffect(() => {
    if (!mapa) return;
    const source = sourceRef.current;

    const vectorLayer = new VectorLayer({
      source,
      style: getStyle(),
    });
    vectorLayerRef.current = vectorLayer;
    mapa.addLayer(vectorLayer);

    // Modify + Snap
    mapa.addInteraction(new Modify({ source }));
    mapa.addInteraction(new Snap({ source }));

    return () => {
      mapa.removeLayer(vectorLayer);
      if (drawRef.current) {
        mapa.removeInteraction(drawRef.current);
        drawRef.current = null;
      }
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mapa]);

  function getStyle() {
    return new Style({
      fill: new Fill({ color: hexToRgba(fillColor, fillOpacity) }),
      stroke: new Stroke({ color: lineColor, width: lineWidth }),
      image: new CircleStyle({
        radius: 7,
        fill: new Fill({ color: lineColor }),
      }),
    });
  }

  function arrowGeometryFunction(
    coordinates: SketchCoordType,
    geometry?: SimpleGeometry,
  ): SimpleGeometry {
    const start = coordinates[0] as number[];
    const end = coordinates[coordinates.length - 1] as number[];
    const dx = end[0] - start[0];
    const dy = end[1] - start[1];
    const rotation = Math.atan2(dy, dx);

    const point1 = [
      end[0] - ARROW_LENGTH * Math.cos(rotation - Math.PI / 6),
      end[1] - ARROW_LENGTH * Math.sin(rotation - Math.PI / 6),
    ];
    const point2 = [
      end[0] - ARROW_LENGTH * Math.cos(rotation + Math.PI / 6),
      end[1] - ARROW_LENGTH * Math.sin(rotation + Math.PI / 6),
    ];

    let g: LineString;
    if (geometry && geometry instanceof LineString) {
      g = geometry;
      g.setCoordinates([start, end, point1, end, point2, end]);
    } else {
      g = new LineString([start, end, point1, end, point2, end]);
    }
    return g;
  }

  function updateDrawInteraction() {
    if (!mapa) return;

    if (drawRef.current) {
      mapa.removeInteraction(drawRef.current);
      drawRef.current = null;
    }
    if (drawType === 'Selecione') return;

    let geometryFunction: GeometryFunction | undefined;
    let type: 'Point' | 'LineString' | 'Polygon' | 'Circle';

    if (drawType === 'Arrow') {
      type = 'LineString';
      geometryFunction = arrowGeometryFunction;
    } else {
      type = drawType;
    }

    const draw = new Draw({
      source: sourceRef.current,
      type,
      freehand,
      geometryFunction,
    });

    draw.on('drawstart', () => {
      if (clearPrevious) sourceRef.current.clear();
    });

    drawRef.current = draw;
    mapa.addInteraction(draw);
  }

  useEffect(() => {
    if (drawRef.current && mapa) {
      mapa.removeInteraction(drawRef.current);
    }
    if (drawType !== 'Selecione') updateDrawInteraction();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [drawType, freehand, clearPrevious]);

  // aplica style quando cor/largura/opacity mudam
  useEffect(() => {
    vectorLayerRef.current?.setStyle(getStyle());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [lineWidth, lineColor, fillColor, fillOpacity]);

  function clearAll() {
    sourceRef.current.clear();
  }

  return (
    <div className="drawing-panel">
      <div className="drawing-header">Desenhar</div>
      <div className="drawing-body">
        <div className="drawing-row">
          <label>Geometria</label>
          <select
            value={drawType}
            onChange={(e) => setDrawType(e.target.value as DrawType)}
          >
            {TYPES.map((t) => (
              <option key={t} value={t}>
                {t}
              </option>
            ))}
          </select>
        </div>

        <div className="drawing-row drawing-check">
          <label>
            <input
              type="checkbox"
              checked={freehand}
              onChange={(e) => setFreehand(e.target.checked)}
            />
            Mão livre (freehand)
          </label>
        </div>
        <div className="drawing-row drawing-check">
          <label>
            <input
              type="checkbox"
              checked={clearPrevious}
              onChange={(e) => {
                setClearPrevious(e.target.checked);
                if (e.target.checked) sourceRef.current.clear();
              }}
            />
            Limpar desenhos anteriores
          </label>
        </div>

        <div className="drawing-row">
          <label>Largura: {lineWidth}</label>
          <input
            type="range"
            min={1}
            max={10}
            value={lineWidth}
            onChange={(e) => setLineWidth(Number(e.target.value))}
          />
        </div>
        <div className="drawing-row">
          <label>Cor da linha</label>
          <input
            type="color"
            value={lineColor}
            onChange={(e) => setLineColor(e.target.value)}
          />
        </div>
        <div className="drawing-row">
          <label>Cor do preenchimento</label>
          <input
            type="color"
            value={fillColor}
            onChange={(e) => setFillColor(e.target.value)}
          />
        </div>
        <div className="drawing-row">
          <label>Opacidade: {Math.round(fillOpacity * 100)}%</label>
          <input
            type="range"
            min={0}
            max={100}
            value={Math.round(fillOpacity * 100)}
            onChange={(e) => setFillOpacity(Number(e.target.value) / 100)}
          />
        </div>

        <div className="drawing-actions">
          <button type="button" className="drawing-clear" onClick={clearAll}>
            Limpar tudo
          </button>
        </div>
      </div>
    </div>
  );
}
