// webgis-react/src/components/webgis/Measure.tsx
// GEO Portal — Measure (portado de measure.component.ts do Angular)
// Medição de distância (LineString) e área (Polygon) com rótulos no mapa.
import { useEffect, useRef, useState } from 'react';
import type { Feature } from 'ol';
import VectorSource from 'ol/source/Vector';
import VectorLayer from 'ol/layer/Vector';
import { Draw, Modify } from 'ol/interaction';
import {
  Circle as CircleStyle,
  Fill,
  RegularShape,
  Stroke,
  Style,
  Text,
} from 'ol/style';
import { LineString, Point, Polygon, type Geometry } from 'ol/geom';
import { getArea, getLength } from 'ol/sphere';
import { useMapa } from '../../contexts/MapaContext';
import './Measure.css';

type MeasureType = 'Select' | 'Point' | 'LineString' | 'Polygon';

const TYPES: MeasureType[] = ['Select', 'LineString', 'Polygon', 'Point'];

function formatLength(line: LineString): string {
  const length = getLength(line);
  return length > 100
    ? `${Math.round((length / 1000) * 100) / 100} km`
    : `${Math.round(length * 100) / 100} m`;
}

function formatArea(polygon: Polygon): string {
  const area = getArea(polygon);
  return area > 10000
    ? `${Math.round((area / 1000000) * 100) / 100} km²`
    : `${Math.round(area * 100) / 100} m²`;
}

function styleFunction(
  feature: Feature<Geometry>,
  segments: boolean,
  drawType: MeasureType,
  tip: string = '',
): Style[] {
  const styles: Style[] = [];
  const geometry = feature.getGeometry();
  if (!geometry) return styles;

  const type = geometry.getType();
  let point: Point | undefined;
  let label: string | undefined;
  let line: LineString | undefined;

  const style = new Style({
    fill: new Fill({ color: 'rgba(255, 255, 255, 0.5)' }),
    stroke: new Stroke({
      color: 'rgba(0, 0, 0, 1)',
      lineDash: [10, 10],
      width: 2,
    }),
    image: new CircleStyle({
      radius: 5,
      stroke: new Stroke({ color: 'rgba(0, 0, 0, 1)' }),
      fill: new Fill({ color: 'rgba(255, 255, 255, 1)' }),
    }),
  });

  const labelStyle = new Style({
    text: new Text({
      font: '14px Calibri,sans-serif',
      fill: new Fill({ color: 'rgba(255, 255, 255, 1)' }),
      backgroundFill: new Fill({ color: 'rgba(0, 0, 0, 0.7)' }),
      padding: [3, 3, 3, 3],
      textBaseline: 'bottom',
      offsetY: -15,
    }),
    image: new RegularShape({
      radius: 8,
      points: 3,
      angle: Math.PI,
      displacement: [0, 10],
      fill: new Fill({ color: 'rgba(0, 0, 0, 0.7)' }),
    }),
  });

  const segmentStyle = new Style({
    text: new Text({
      font: '12px Calibri,sans-serif',
      fill: new Fill({ color: 'rgba(255, 255, 255, 1)' }),
      backgroundFill: new Fill({ color: 'rgba(0, 0, 0, 0.4)' }),
      padding: [2, 2, 2, 2],
      textBaseline: 'bottom',
      offsetY: -12,
    }),
    image: new RegularShape({
      radius: 6,
      points: 3,
      angle: Math.PI,
      displacement: [0, 8],
      fill: new Fill({ color: 'rgba(0, 0, 0, 0.4)' }),
    }),
  });

  if (drawType === type) {
    styles.push(style);
    if (type === 'Polygon' && geometry instanceof Polygon) {
      point = geometry.getInteriorPoint();
      label = formatArea(geometry);
      line = new LineString(geometry.getCoordinates()[0]);
    } else if (type === 'LineString' && geometry instanceof LineString) {
      point = new Point(geometry.getLastCoordinate());
      label = formatLength(geometry);
      line = geometry;
    }
  }

  if (segments && line) {
    line.forEachSegment((a, b) => {
      const segment = new LineString([a, b]);
      const segmentLabel = formatLength(segment);
      segmentStyle.setGeometry(new Point(segment.getCoordinateAt(0.5)));
      segmentStyle.getText()?.setText(segmentLabel);
      styles.push(segmentStyle);
    });
  }

  if (label && point) {
    labelStyle.setGeometry(point);
    labelStyle.getText()?.setText(label);
    styles.push(labelStyle);
  }

  if (tip && type === 'Point') {
    const tipStyle = new Style({
      text: new Text({
        font: '12px Calibri,sans-serif',
        fill: new Fill({ color: 'rgba(255, 255, 255, 1)' }),
        backgroundFill: new Fill({ color: 'rgba(0, 0, 0, 0.4)' }),
        padding: [2, 2, 2, 2],
        textAlign: 'left',
        offsetX: 15,
      }),
    });
    tipStyle.getText()?.setText(tip);
    tipStyle.setGeometry(geometry);
    styles.push(tipStyle);
  }

  return styles;
}

export default function Measure() {
  const { mapa } = useMapa();
  const sourceRef = useRef(new VectorSource());
  const vectorLayerRef = useRef<VectorLayer<VectorSource> | null>(null);
  const modifyRef = useRef<Modify | null>(null);
  const drawRef = useRef<Draw | null>(null);

  const [drawType, setDrawType] = useState<MeasureType>('Select');
  const [showSegments, setShowSegments] = useState(true);
  const [clearPrevious, setClearPrevious] = useState(false);

  useEffect(() => {
    if (!mapa) return;
    const source = sourceRef.current;

    const modify = new Modify({ source });
    modifyRef.current = modify;

    const vectorLayer = new VectorLayer<VectorSource>({
      source,
      style: (feature) =>
        styleFunction(feature as Feature<Geometry>, showSegments, drawType),
    });
    vectorLayerRef.current = vectorLayer;

    mapa.addLayer(vectorLayer);
    mapa.addInteraction(modify);

    return () => {
      mapa.removeLayer(vectorLayer);
      mapa.removeInteraction(modify);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [mapa]);

  // (re)adiciona a interação de draw sempre que mudar o tipo
  useEffect(() => {
    if (!mapa) return;
    if (drawRef.current) {
      mapa.removeInteraction(drawRef.current);
      drawRef.current = null;
    }
    if (drawType === 'Select') {
      modifyRef.current?.setActive(true);
      return;
    }

    let tip = 'Click to start measuring';
    const draw = new Draw({
      source: sourceRef.current,
      type: drawType,
      style: (feature) =>
        styleFunction(feature as Feature<Geometry>, showSegments, drawType, tip),
    });

    draw.on('drawstart', () => {
      if (clearPrevious) sourceRef.current.clear();
      modifyRef.current?.setActive(false);
      tip =
        drawType === 'Polygon'
          ? 'Click to continue drawing the polygon'
          : 'Click to continue drawing the line';
    });

    draw.on('drawend', (event) => {
      const feature = event.feature;
      feature.setStyle(
        styleFunction(feature as Feature<Geometry>, showSegments, drawType),
      );
      modifyRef.current?.setActive(true);
      tip = 'Click to start measuring';
      vectorLayerRef.current?.changed();
    });

    drawRef.current = draw;
    mapa.addInteraction(draw);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [drawType, showSegments, clearPrevious, mapa]);

  function onSegmentChange() {
    vectorLayerRef.current?.changed();
  }

  function clearAll() {
    sourceRef.current.clear();
  }

  return (
    <div className="measure-panel">
      <div className="measure-header">Medir</div>
      <div className="measure-body">
        <div className="measure-row">
          <label>Tipo</label>
          <select value={drawType} onChange={(e) => setDrawType(e.target.value as MeasureType)}>
            {TYPES.map((t) => (
              <option key={t} value={t}>
                {t}
              </option>
            ))}
          </select>
        </div>
        <div className="measure-row measure-check">
          <label>
            <input
              type="checkbox"
              checked={showSegments}
              onChange={(e) => {
                setShowSegments(e.target.checked);
                onSegmentChange();
              }}
            />
            Mostrar segmentos
          </label>
        </div>
        <div className="measure-row measure-check">
          <label>
            <input
              type="checkbox"
              checked={clearPrevious}
              onChange={(e) => setClearPrevious(e.target.checked)}
            />
            Limpar medições anteriores
          </label>
        </div>
        <div className="measure-actions">
          <button type="button" className="measure-clear" onClick={clearAll}>
            Limpar medições
          </button>
        </div>
      </div>
    </div>
  );
}

// webgis/src/app/paginas/webgis/componentes/measure/measure.component.ts
import { Component, OnInit } from '@angular/core';
import { Draw, Modify } from 'ol/interaction';
import { Vector as VectorSource } from 'ol/source';
import { Vector as VectorLayer } from 'ol/layer';
import {
  Style,
  Fill,
  Stroke,
  Text,
  Circle as CircleStyle,
  RegularShape,
} from 'ol/style';
import { Geometry, LineString, Point, Polygon } from 'ol/geom';
import { MapaService } from 'src/app/services/mapa.service';
import { Feature, Map } from 'ol';
import { getArea, getLength } from 'ol/sphere';
import { FormsModule } from '@angular/forms';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { NgIf } from '@angular/common';
import { MatCardModule } from '@angular/material/card';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { Observable, Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';
import { MatTooltip } from '@angular/material/tooltip';
import {
  MAT_SLIDE_TOGGLE_DEFAULT_OPTIONS,
  MatSlideToggleModule,
} from '@angular/material/slide-toggle';

@Component({
  selector: 'app-measure',
  standalone: true,
  imports: [
    FormsModule,
    MatIconModule,
    MatButtonModule,
    MatCardModule,
    MatFormFieldModule,
    MatSelectModule,
    FormsModule,
    MatCheckboxModule,
    MatTooltip,
    MatSlideToggleModule,
  ],
  providers: [
    {
      provide: MAT_SLIDE_TOGGLE_DEFAULT_OPTIONS,
      useValue: {
        color: '#2e7d32',
      },
    },
  ],
  templateUrl: './measure.component.html',
  styleUrls: ['./measure.component.scss'],
})
export class MeasureComponent implements OnInit {
  draw!: Draw;
  source!: VectorSource;
  vectorLayer!: VectorLayer<VectorSource>;
  modify!: Modify;
  drawType:
    | 'Select'
    | 'Point'
    | 'LineString'
    | 'Polygon'
    | 'Circle'
    | 'MultiPoint'
    | 'MultiLineString'
    | 'MultiPolygon' = 'Select';
  showSegments: boolean = true;
  clearPrevious: boolean = false;
  private map$!: Observable<Map>;
  private mapSubscription!: Subscription;

  constructor(private mapaService: MapaService) {}

  ngOnInit(): void {
    this.map$ = this.mapaService
      .getMapaObservable()
      .pipe(filter((map): map is Map => map !== null));
    this.mapSubscription = this.map$.subscribe((map) => {
      this.initializeMap(map);

      const layers = map.getLayers();
      const handleLayerAdd = () => {
        layers.un('add', handleLayerAdd);
        this.bringVectorLayerToTop(map);
        layers.on('add', handleLayerAdd);
      };

      layers.on('add', handleLayerAdd);
    });
  }

  bringVectorLayerToTop(map: Map): void {
    map.removeLayer(this.vectorLayer);
    map.addLayer(this.vectorLayer);
  }

  ngOnDestroy(): void {
    if (this.mapSubscription) {
      this.mapSubscription.unsubscribe();
    }
  }

  initializeMap(map: Map): void {
    this.source = new VectorSource();
    this.modify = new Modify({ source: this.source });

    this.vectorLayer = new VectorLayer<VectorSource>({
      source: this.source,
      style: (feature) =>
        this.styleFunction(
          feature as Feature<Geometry>,
          this.showSegments,
          this.drawType,
          '',
        ),
    });

    map.addLayer(this.vectorLayer);
    map.addInteraction(this.modify);
  }
  addInteraction(map: Map): void {
    if (this.draw) {
      map.removeInteraction(this.draw);
    }

    if (this.drawType === 'Select') {
      return;
    }

    const activeTip = `Click to continue drawing the ${
      this.drawType === 'Polygon' ? 'polygon' : 'line'
    }`;
    const idleTip = 'Click to start measuring';
    let tip = idleTip;

    this.draw = new Draw({
      source: this.source,
      type: this.drawType,
      style: (feature) =>
        this.styleFunction(
          feature as Feature<Geometry>,
          this.showSegments,
          this.drawType,
          tip,
        ),
    });

    this.draw.on('drawstart', () => {
      if (this.clearPrevious) {
        this.source.clear();
      }
      this.modify.setActive(false);
      tip = activeTip;
    });

    this.draw.on('drawend', (event) => {
      const feature = event.feature;
      feature.setStyle(
        this.styleFunction(feature, this.showSegments, this.drawType),
      );
      this.modify.setActive(true);
      tip = idleTip;
      this.vectorLayer.changed();
    });

    this.modify.setActive(true);
    map.addInteraction(this.draw);
  }

  styleFunction(
    feature: Feature<Geometry>,
    segments: boolean,
    drawType: string,
    tip: string = '',
  ): Style[] {
    const styles: Style[] = [];
    const geometry = feature.getGeometry();

    if (!geometry) {
      return styles;
    }

    const type = geometry.getType();
    let point: Point | undefined;
    let label: string | undefined;
    let line: LineString | undefined;

    const style = new Style({
      fill: new Fill({
        color: 'rgba(255, 255, 255, 0.5)',
      }),
      stroke: new Stroke({
        color: 'rgba(0, 0, 0, 1)',
        lineDash: [10, 10],
        width: 2,
      }),
      image: new CircleStyle({
        radius: 5,
        stroke: new Stroke({
          color: 'rgba(0, 0, 0, 1)',
        }),
        fill: new Fill({
          color: 'rgba(255, 255, 255, 1)',
        }),
      }),
    });

    const labelStyle = new Style({
      text: new Text({
        font: '14px Calibri,sans-serif',
        fill: new Fill({
          color: 'rgba(255, 255, 255, 1)',
        }),
        backgroundFill: new Fill({
          color: 'rgba(0, 0, 0, 0.7)',
        }),
        padding: [3, 3, 3, 3],
        textBaseline: 'bottom',
        offsetY: -15,
      }),
      image: new RegularShape({
        radius: 8,
        points: 3,
        angle: Math.PI,
        displacement: [0, 10],
        fill: new Fill({
          color: 'rgba(0, 0, 0, 0.7)',
        }),
      }),
    });

    const segmentStyle = new Style({
      text: new Text({
        font: '12px Calibri,sans-serif',
        fill: new Fill({
          color: 'rgba(255, 255, 255, 1)',
        }),
        backgroundFill: new Fill({
          color: 'rgba(0, 0, 0, 0.4)',
        }),
        padding: [2, 2, 2, 2],
        textBaseline: 'bottom',
        offsetY: -12,
      }),
      image: new RegularShape({
        radius: 6,
        points: 3,
        angle: Math.PI,
        displacement: [0, 8],
        fill: new Fill({
          color: 'rgba(0, 0, 0, 0.4)',
        }),
      }),
    });

    const formatLength = (line: LineString) => {
      const length = getLength(line);
      return length > 100
        ? `${Math.round((length / 1000) * 100) / 100} km`
        : `${Math.round(length * 100) / 100} m`;
    };

    const formatArea = (polygon: Polygon) => {
      const area = getArea(polygon);
      return area > 10000
        ? `${Math.round((area / 1000000) * 100) / 100} km²`
        : `${Math.round(area * 100) / 100} m²`;
    };

    if (drawType === type) {
      styles.push(style);
      if (type === 'Polygon' && geometry instanceof Polygon) {
        point = geometry.getInteriorPoint();
        label = formatArea(geometry);
        line = new LineString(geometry.getCoordinates()[0]);
      } else if (type === 'LineString' && geometry instanceof LineString) {
        point = new Point(geometry.getLastCoordinate());
        label = formatLength(geometry);
        line = geometry;
      }
    }

    if (segments && line) {
      line.forEachSegment((a, b) => {
        const segment = new LineString([a, b]);
        const segmentLabel = formatLength(segment);
        const segmentPoint = new Point(segment.getCoordinateAt(0.5));
        segmentStyle.setGeometry(segmentPoint);

        const text = segmentStyle.getText();
        if (text) {
          text.setText(segmentLabel);
        }

        styles.push(segmentStyle);
      });
    }

    if (label && point) {
      labelStyle.setGeometry(point);
      const text = labelStyle.getText();
      if (text) {
        text.setText(label);
      }
      styles.push(labelStyle);
    }

    if (tip && type === 'Point') {
      const tipStyle = new Style({
        text: new Text({
          font: '12px Calibri,sans-serif',
          fill: new Fill({
            color: 'rgba(255, 255, 255, 1)',
          }),
          backgroundFill: new Fill({
            color: 'rgba(0, 0, 0, 0.4)',
          }),
          padding: [2, 2, 2, 2],
          textAlign: 'left',
          offsetX: 15,
        }),
      });
      const text = tipStyle.getText();
      if (text) {
        text.setText(tip);
      }
      tipStyle.setGeometry(geometry);
      styles.push(tipStyle);
    }

    return styles;
  }

  onTypeChange(): void {
    this.map$.subscribe((map) => {
      if (map) {
        if (this.draw) {
          map.removeInteraction(this.draw);
        }
        this.addInteraction(map);
      }
    });
  }

  onSegmentChange(): void {
    this.vectorLayer.changed();
  }

  clearAllSegments(): void {
    this.source.clear();
  }
}

<!-- ── Header ─────────────────────────────────────────────────────────────── -->
<div class="panel-header">
  <div class="panel-title">
    <svg width="14" height="14" viewBox="0 0 24 24" fill="none" aria-hidden="true">
      <path d="M3 21L21 3" stroke="#01499B" stroke-width="1.8" stroke-linecap="round"/>
      <path d="M6.5 17.5l1.8-1.8M10.5 13.5l1.8-1.8M14.5 9.5l1.8-1.8"
            stroke="#01499B" stroke-width="1.5" stroke-linecap="round"/>
    </svg>
    <span class="panel-label">Medir</span>
  </div>
</div>

<!-- ── Tipo de medida ──────────────────────────────────────────────────────── -->
<div class="field-group">
  <span class="field-label">Tipo de medida</span>
  <div class="select-wrap">
    <mat-select name="measurementType" [(ngModel)]="drawType" (selectionChange)="onTypeChange()" panelClass="webgis-select-panel">
      <mat-option value="Select">Selecionar</mat-option>
      <mat-option value="LineString">Comprimento (Linha)</mat-option>
      <mat-option value="Polygon">Área (Polígono)</mat-option>
    </mat-select>
  </div>
</div>

<!-- ── Toggles ─────────────────────────────────────────────────────────────── -->
<div class="toggles">
  <div class="toggle-row" (click)="showSegments = !showSegments; onSegmentChange()">
    <span class="toggle-text">Mostrar segmentos</span>
    <div class="toggle-wrap" [class.toggle-on]="showSegments">
      <div class="toggle-track"><div class="toggle-thumb"></div></div>
    </div>
  </div>

  <div class="toggle-row" (click)="clearPrevious = !clearPrevious">
    <span class="toggle-text">Limpar anteriores</span>
    <div class="toggle-wrap" [class.toggle-on]="clearPrevious">
      <div class="toggle-track"><div class="toggle-thumb"></div></div>
    </div>
  </div>
</div>

<!-- ── Ação ───────────────────────────────────────────────────────────────── -->
<button class="clear-btn" (click)="clearAllSegments()" type="button">
  <svg width="13" height="13" viewBox="0 0 24 24" fill="none">
    <path d="M3 6h18M8 6V4h8v2M19 6l-1 14H6L5 6" stroke="currentColor" stroke-width="1.7"
          stroke-linecap="round" stroke-linejoin="round"/>
  </svg>
  Limpar medidas
</button>
